[package]
name = "p1"
version = "0.1.0"
authors = ["Andrei Oproiu <andrei.r.oproiu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
statistical = "1.0.0"